---
Name: rootroutes
---
Director:
  rules:
    'room//$Action/$ID': 'RoomController'
    'register//$Action/$ID': 'RegistrationController'
    'song': 'SongSearchController'
    '$Action': 'MainController'